config/routes.rb
Rails.application.routes.draw do
  
  resources :genres

  resources :favorites

  resource :session
  get "signup" => "users#new"
  get "signin" => "sessions#new"

  resources :users

  root "movies#index"
  resources :movies do
    resources :reviews
  end
end

app/models/genre.rb
class Genre < ActiveRecord::Base

	# a has_many association with characterizations
	has_many :characterizations, dependent: :destroy

	# a has_many association with movies that goes through the characterizations association.
	has_many :movies, through: :characterizations

	# add validations to ensure that a genre always has a non-blank and unique name
	validates :name, presence: true, uniqueness: true
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

before_action :require_signin, except: [:index, :show]
before_action :require_admin, except: [:index, :show]

  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
    @movies = @genre.movies
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to @genre, notice: "Genre successfully updated!"
    else
      render :edit
    end
  end

  def new
    @genre = Genre.new
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to @genre, notice: "Genre successfully created!"
    else
      render :new
    end
  end
  
  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to genres_url, alert: "Genre successfully deleted!"
  end
  

private

  def genre_params
    params.require(:genre).permit(:name, movie_ids: [])
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_for(@genre) do |f| %>
  <%= render "shared/errors", object: @genre %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true %>
      </li>
    </ol>
    <p>
      <%= f.submit %>
      <%= link_to "Cancel",genres_path, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/genres/edit.html.erb
<header id="content-header">
  <h1>Editing <%= @genre.name %></h1>
</header>

<%= render 'form' %>

app/views/genres/index.html.erb
<ul id="genres">
  <% @genres.each do |genre| %>
    <li>
      <article class="genre" id="<%= dom_id(genre) %>">
        <header>
        
          <h2><%= link_to genre.name, genre %></h2>
        </header>
        <footer>
        </footer>
      </article>
    </li>
  <% end %>
</ul>

app/views/genres/new.html.erb
<header id="content-header">
  <h1>Create a New Genre</h1>
</header>

<%= render 'form' %>

app/views/genres/show.html.erb
<article id="genre" class="genre">
  <header>
    <h1><%= @genre.name %></h1>
</header>

  <h3>Movies</h3>
  <ul>
    <% @movies.each do |movie| %>
      <li><%= movie.title %></li>
    <% end %>
  </ul>
    
  <footer>
  <nav>

    <% if current_user_admin? %> 
      <!-- Hide links from folks who aren't Admins-->
    
      <%= link_to 'Edit', edit_genre_path(@genre), class: 'button' %>
      <%= link_to 'Delete', @genre, 
                  class: 'button',
                  method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>

    </nav>
  </footer>
</article>